const contluminosos = {
    amada2: "Amada Divinidad, Padre, Hijo y Espíritu Santo. Entro en tu querer divino, tomo y hago mío tu poder, la inmensidad de tu amor, tus actos, obras, penas y cualidades divinas en tu Santísima Humanidad para girar a través de este Santo Rosario, con ello sello, bendigo y consagro a todas las creaturas de todas las generaciones, Santísima Trinidad en tu divino amor te abrazo y empiezo.",

    santo2: "Me fundo en el orden de tu Gracia, en todo lo que has hecho y harás en nosotros los santificantes.\n 									   ¡Ven Divino Espíritu!, haz desahogo de Tu obra en el Fiat Voluntas Tua. Danos pronto a conocer vuestra Voluntad, para que conociéndola, amemos y acojamos Tu primer acto completo, el cual es, La Divina Voluntad.",

    giro2: "Me Fundo en ti Jesús y en Tu Divina Voluntad y sumergida en Tu agua bautismal, inicio mi recorrido en tus Misterios Luminosos.\n En tu acto único y eterno recibo tu Bendición Celestial en las Bodas celebradas por Ti y me presento ante tu Suprema Majestad como apóstol, dándote la Gloria a nombre de cada una de las criaturas de todos los tiempos proclamando el Reino de tu Divina Voluntad con mi vida.\n Transfigurado amor mío, te agradezco por haberte mostrado anticipadamente, por tus palabras Divinas y por quedarte para darte a todos en el Sacramento de la Eucaristía.\n A nombre de todos te doy mi te amo, te Alabo, te Bendigo, te Glorifico y junto a la Virgen María, a Luisa, a toda la Iglesia militante, triunfante y purgante te pido que, 'Venga tu Reino'.\n Ven Divina Voluntad a rezar en mí,",

    acto2: "Dios mío, perdóname; yo tuve la osadía de ofenderte y de rebelarme contra ti en el mismo instante en que Tú me Amabas.\n Me arrepiento de todo corazón de haberte ofendido.\n     Te ruego, te suplico que me concedas tu amargura, a fin de poder dolerme con ese mismo dolor con el que tú te doliste por mis pecados; dolor tan grande e intenso que te hizo sudar sangre.\n Madre Celestial, alcánzame de tu Jesús el suspirado perdón.\n 																     Yo propongo y prometo del modo más enérgico y absoluto nunca más volver a pecar. Amén.",

    credo2: "Creo en Dios, Padre Todopoderoso, Creador del cielo y de la tierra.\n 													   Creo en Jesucristo su único Hijo Nuestro Señor, que fue concebido por obra y gracia del Espíritu Santo.\n 										  Nació de Santa María Virgen, padeció bajo el poder de Poncio Pilato, fue crucificado, muerto y sepultado, descendió a los infiernos, al tercer día resucitó de entre los muertos, subió a los cielos y está sentado a la derecha de Dios Padre, todopoderoso. Desde allí va a venir a juzgar a vivos y muertos.\n 									   Creo en el Espíritu Santo, la Santa Iglesia católica, la comunión de los santos, el perdón de los pecados, la resurrección de la carne y la vida eterna. Amén",

    miste2: "1) El bautismo de Jesús en el Jordán.\n 2) Las Bodas de Caná.\n 3) El Anuncio del Reino.\n 4) La Transfiguración.\n 5) La Institución de la Eucaristía.."

};
