const contgloriosos = {
    amada: "Amada Divinidad, Padre, Hijo y Espíritu Santo. Entro en tu querer divino, tomo y hago mío tu poder, la inmensidad de tu amor, tus actos, obras, penas y cualidades divinas en tu Santísima Humanidad para girar a través de este Santo Rosario, con ello sello, bendigo y consagro a todas las creaturas de todas las generaciones, Santísima Trinidad en tu divino amor te abrazo y empiezo.",

    santo: "Me fundo en el orden de tu Gracia, en todo lo que has hecho y harás en nosotros los santificantes.\n 									   ¡Ven Divino Espíritu!, haz desahogo de Tu obra en el Fiat Voluntas Tua. Danos pronto a conocer vuestra Voluntad, para que conociéndola, amemos y acojamos Tu primer acto completo, el cual es, La Divina Voluntad.",

    giro: "Jesús, me fundo en ti y en tu Divina Voluntad y entro en Tu acto único y eterno; y desde el Cenáculo, junto a Luisa y en el corazón de María, me sumerjo en tu Querer Divino para hacer el paseo de mi alma en Tus Misterios Gloriosos, en compañía de toda la Iglesia Militante, Purgante y Triunfante.\n\n								 Padre, gracias por darnos a María como Reina y Madre para que nos enseñe al igual que a los apóstoles la vida de tu Hijo; todo lo que Ella vivió en Él y Jesús en Ella y todo lo que quieres que nosotros vivamos bajo su guía y protección para este Reino Divino. Y, pronunciamos nuestro Fiat en el FIAT de María, abandonados como los más pequeños Hijos de tu Divina Voluntad.\n    Oh Santísima Trinidad, con la meditación de estos misterios, en Jesús Glorificado, te doy mi Te amo con tu Voluntad, Te adoro, Te bendigo, Te abrazo, Te beso y Te doy gracias a nombre mío, de todos y por todos pidiendo Venga a nosotros Tu Reino. Hágase tu Voluntad como en el Cielo así en la tierra.\n Santísima Trinidad, te abrazo y empiezo.",

    acto: "Dios mío, perdóname; yo tuve la osadía de ofenderte y de rebelarme contra ti en el mismo instante en que Tú me Amabas.\n Me arrepiento de todo corazón de haberte ofendido.\n     Te ruego, te suplico que me concedas tu amargura, a fin de poder dolerme con ese mismo dolor con el que tú te doliste por mis pecados; dolor tan grande e intenso que te hizo sudar sangre.\n Madre Celestial, alcánzame de tu Jesús el suspirado perdón.\n 																     Yo propongo y prometo del modo más enérgico y absoluto nunca más volver a pecar. Amén.",

    credo: "Creo en Dios, Padre Todopoderoso, Creador del cielo y de la tierra.\n 													   Creo en Jesucristo su único Hijo Nuestro Señor, que fue concebido por obra y gracia del Espíritu Santo.\n 										  Nació de Santa María Virgen, padeció bajo el poder de Poncio Pilato, fue crucificado, muerto y sepultado, descendió a los infiernos, al tercer día resucitó de entre los muertos, subió a los cielos y está sentado a la derecha de Dios Padre, todopoderoso. Desde allí va a venir a juzgar a vivos y muertos.\n 									   Creo en el Espíritu Santo, la Santa Iglesia católica, la comunión de los santos, el perdón de los pecados, la resurrección de la carne y la vida eterna. Amén",

    miste: "1) La resurrección de Jesús.\n 2) La Ascención de Jesús al Cielo.\n 3) La venida del El Espíritu Santo sobre el Colegio apostólico.\n 4) La Asunción de María Santísima al Cielo. \n 5) La Coronación de María Santísima Madre y Reina de la Divina Voluntad."

};
